### ISSUE TITLE
py-rattler from Conda-Forge doesn't use system's SSL certificates

### ISSUE THREAD

**Issue by JanJaguschQC** [conda/rattler#961]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

The `py-rattler` release (v0.8.2) on Conda-Forge doesn't use the system's SSL certificates. This is the error we're observing:

```
invalid peer certificate: UnknownIssuer
```

I suspect that [this commit](https://github.com/conda-forge/py-rattler-feedstock/commit/60508a20eaaddf5ca6d18d41e82eb8670f4e91d5) broke this functionality when switching to the `native-tls` feature.

Is it possible that the `native-tls` feature in `py-rattler` is missing dependencies? For comparision:

Pixi (which finds the system's SSL certificates): 
https://github.com/prefix-dev/pixi/blob/c0040f5967986f07f281002865e392a9b0d960ce/Cargo.toml#L159-L165
```toml
native-tls = [
  "reqwest/native-tls",
  "reqwest/native-tls-alpn",
  "rattler_repodata_gateway/native-tls",
  "rattler/native-tls",
  "pixi_utils/native-tls",
]
```

py-rattler:
https://github.com/conda/rattler/blob/104a5216e50facf88c2b81405f66309ed1a134f5/py-rattler/Cargo.toml#L14-L17

Note that we discovered a similar problem with the PyPI release (that uses `rusttls-tls`) a couple of days ago: https://github.com/conda/rattler/pull/957

**Comment by wolfv** [comment]
I think this was recently fixed by #957?

**Comment by wolfv** [comment]
By yourself!? :) 

Not released yet, I think.

**Comment by baszalmstra** [comment]
We need to cut a new release indeed. However we are a little bit in a transition period with a nee oock format which means I have to hold of for a release just a bit longer.

**Comment by JanJaguschQC** [comment]
> By yourself!? :)
> 
> Not released yet, I think.

Not quite. https://github.com/conda/rattler/pull/957 should have fixed the PyPI release (`rusttls`). But the Conda-Forge release (`openssl`) is still broken.

**Comment by baszalmstra** [comment]
It indeed looks like we are not properly linking with openssl on conda-forge. I created a PR on the feedstock to hopefully fix this: https://github.com/conda-forge/py-rattler-feedstock/pull/32
